# --- معلومات المشروع الأساسية ---
name: uquts1
description: "تطبيق لإدارة معامل جامعة أم القرى"

# منع النشر العرضي للحزمة على pub.dev.
publish_to: 'none'

# إصدار التطبيق.
# version: 1.0.0+1 -> رقم الإصدار + رقم البناء (build number).
version: 1.0.0+1

#------------------------------------------------------------------------------

# --- بيئة التشغيل ---
environment:
  # تحديد إصدارات Dart SDK المتوافقة مع المشروع.
  sdk: '>=3.0.0 <4.0.0'
  # تحديد إصدار Flutter المتوافق.
  flutter: ">=3.16.0"

#------------------------------------------------------------------------------

# --- الاعتماديات (Dependencies) ---
# الحزم التي يعتمد عليها التطبيق في وضعي التطوير والإنتاج.
dependencies:
  # الاعتماديات الأساسية من Flutter SDK.
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Firebase ---
  # الحزم الأساسية للتكامل مع خدمات Firebase.
  firebase_core: ^2.24.2 # الحزمة الأساسية لتهيئة Firebase.
  cloud_firestore: ^4.15.11 # للتفاعل مع قاعدة بيانات Firestore.
  firebase_storage: ^11.6.5 # لتخزين الملفات مثل الصور.

  # --- قاعدة البيانات المحلية (Local Database) ---
  # (ملاحظة: قد لا تكون مستخدمة إذا كان الاعتماد كليًا على Firebase)
  sqflite: ^2.3.2 # قاعدة بيانات SQLite محلية.
  path: ^1.8.3 # للتعامل مع مسارات الملفات.
  path_provider: ^2.1.2 # للحصول على مسارات التخزين في الجهاز.

  # --- WebView وفتح الروابط ---
  webview_flutter: ^4.4.2 # لعرض صفحات الويب داخل التطبيق.
  webview_flutter_platform_interface: ^2.4.0
  url_launcher: ^6.2.2 # لفتح الروابط في المتصفح الخارجي.

  # --- الصور ---
  image_picker: ^1.0.7 # لاختيار الصور من الكاميرا أو المعرض.
  flutter_image_compress: ^2.4.0 # لضغط الصور وتقليل حجمها.

  # --- QR/Barcode ---
  mobile_scanner: ^7.0.1 # ماسح ضوئي فعال للباركود و QR.
  barcode_widget: ^2.0.4 # لإنشاء وعرض ويدجت للباركود.
  # استخدام نسخة معدلة من حزمة المسح الضوئي مباشرة من GitHub.
  flutter_barcode_scanner:
    git:
      url: https://github.com/decodevM/flutter_barcode_scanner.git
      ref: master

  # --- مكونات واجهة المستخدم (UI Components) ---
  cupertino_icons: ^1.0.6 # أيقونات بتصميم iOS.
  google_fonts: ^6.1.0 # للوصول إلى مكتبة خطوط جوجل.
  flutter_svg: ^2.0.10 # لعرض الصور بصيغة SVG.

  # --- أدوات مساعدة (Utils) ---
  uuid: ^4.3.3 # لتوليد معرفات فريدة عالميًا (UUIDs).
  share_plus: ^11.0.0 # لمشاركة المحتوى مع تطبيقات أخرى.
  shared_preferences: ^2.2.2 # لتخزين البيانات البسيطة محليًا (مثل إعدادات المستخدم).

#------------------------------------------------------------------------------

# --- اعتماديات التطوير (Dev Dependencies) ---
# الحزم التي يحتاجها المشروع فقط أثناء عملية التطوير والاختبار.
dev_dependencies:
  flutter_test:
    sdk: flutter
  # مجموعة من قواعد التحليل (linting) لتحسين جودة الكود واتباع أفضل الممارسات.
  flutter_lints: ^3.0.1

#------------------------------------------------------------------------------

# --- إعدادات خاصة بـ Flutter ---
flutter:
  # تفعيل استخدام تصميم Material.
  uses-material-design: true
  
  # تعريف الأصول (Assets) التي يستخدمها التطبيق.
  assets:
    - assets/ # تعريف المجلد بالكامل
    - assets/fonts/ # تعريف مجلد الخطوط
    - assets/images/uquLogo.png # تعريف صورة محددة
    
  # تعريف الخطوط المخصصة المضمنة في التطبيق.
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
