name: uquts1
description: "تطبيق لإدارة معامل جامعة أم القرى"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Database
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  
  # WebView and URL
  webview_flutter: ^4.4.2
  webview_flutter_platform_interface: ^2.4.0
  url_launcher: ^6.2.2
  
  # Image Picker
  image_picker: ^1.0.7
  
  # QR/Barcode
  mobile_scanner: ^3.5.6
  barcode_widget: ^2.0.4
  flutter_barcode_scanner:
    git:
      url: https://github.com/decodevM/flutter_barcode_scanner.git
      ref: master
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Utils
  uuid: ^4.3.3
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/fonts/
    - assets/images/uquLogo.png
    
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
